const { longestWordString } = require("./01-longest Word String")
const { longestWordString2 } = require("./02-longest Word String")
const { firstReverse } = require("./03-First Reverse String")
const { usernameValidation } = require("./04-Validation String")
const { timesOfMostFreqChar } = require("./05-Times Of Most String")
const { reverseEachWord } = require("./06-Reverse Each Word String")
const { commonCharacters } = require("./07-Common Characters String")
const { firstNonRepeatedCharacter } = require("./08-first Non Repeated Character String")
const { onlyUnique } = require("./09-Only Unique String")
const { characterFrequency } = require("./10-Character Frequency String")
const { checkStringsAnagram } = require("./11-Check Two Strings")
const { checkIfStringHasOnlyDigits } = require("./12-Check Digits Strings")
const { findMissingLetterIn } = require("./13-Missing String")
const { lessWordString } = require("./14-Word LastLength String")
const { isUnique } = require("./15-Unique String")
const { countVowels, prodectsFirstLetters } = require("./16-Vowels String")
const { isStrRotation } = require("./17-Rotation String")
const { reverseRecursion } = require("./18-Reverse Recursion String")
const { isPermutation, permutations } = require("./19-Permutations String")
const { findDuplicateCharacter } = require("./20-Find Duplicate String")
const { countCharacter } = require("./21-Count Duplicate String")
const { maxCharTime } = require("./22-Duplicate Maxmin String")
const { removeDuplicateChar } = require("./23-Remove Duplicate String")
const { findMaxMin } = require("./24-Max Min Array")
const { mergeSortedArray } = require("./25-Sort Merge Array")
const { topSum } = require("./26-Sum Two Largest Array")
const { longestSequence } = require("./27-Longest Sequence Array")
const { largestPossibleSum } = require("./28-Largest Possible Sum Array")
const { ArrayMiddle } = require("./29-Array Middle Array")
const { evenOccurrence } = require("./30-Even Occurrence Array")
const { largestProductOfThree } = require("./31-Largest Product Of Three Array")
const { missingNumber } = require("./32-Missing Array")
const { average } = require("./33-Average Array")
const { findIntersection } = require("./34-Find Intersection Array")
const { sumArrayOdd } = require("./35-Sum Odd Array")
const { twoSum } = require("./36-Sum Pairs Array")
const { sumFinder } = require("./37-Sum Finder Array")
const { primeFactors, prime, largetPrimeFactor } = require("./38-Prime Factors Number")
const { convert, reverse } = require("./39-Reverse Number")
const { swapNumb } = require("./40-Swap Number")
const { isPrime } = require("./41-Prime Check Number")
const { negativePositive } = require("./42-Negative Positive Number")
const { evenOrNot } = require("./43-Even or Not Number")
const { removeDuplicates } = require("./44-Duplicate Remove Number")
const { uniqueItems } = require("./45-Unique Item Number")
const { countDuplicate } = require("./46-Duplicate Count Number")
const { isPowerOfTwo } = require("./47-Is Power Of Two Number")
const { factorialize } = require("./48-Factorial Number")
const { addCommasAndUnderscore } = require("./49-Commas Underscore Number")
const { findDuplicate } = require("./50-Duplicate Find Number")
const { greatestCommonDivisor, findGCD } = require("./51-Common Divisor Number (GCD)")
const { countZero } = require("./52-Count Zero Number")
const { fun1 } = require("./53-Calculator")
const { convertToBinary } = require("./54-Convert To Binary")
const { reverseInteger } = require("./55-Reverse Integer")
const { floydTriangle } = require("./56-Floyd Triangle")
require("./57-Pascal Triangle")
require("./58-Sum Without Operator")
require("./59-Pyramid")
require("./60-FirstEvenAndSecaundOdd")



