require("./01-Introduction To JavaScript")
require("./02_Functions In JavaScript")
require("./03-Conditionals in JavaScript")
require("./04-Variables In JavaScript")
require("./05-Arrays in JavaScript")
require("./06-Objects in JavaScript")
require("./07-Iteration in JavaScript")
require("./08-Recursion In JavaScript")
require("./09-Callbacks and higher order functions")
require("./10-Closures And Object Oriented Programming")